apiVersion : apps/v1
kind: Deployment
metadata:
  name: postgres-erp
spec:
  selector:
      matchLabels:
        app: postgres-erp-dep
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres-erp-dep
    spec:
      containers:
        - name: postgres-erp
          image: postgres:latest
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-erp-config
          volumeMounts:
            - mountPath: /data
              name: postgredb-erp
      volumes:
        - name: postgredb-erp
          persistentVolumeClaim:
            claimName: postgres-erp-pv-claim