kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-erp-pv-volume
  labels:
    type: local
    app: postgres-erp
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"