kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-erp-pv-claim
  labels:
    app: postgres-erp
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi