apiVersion : apps/v1
kind: Deployment
metadata:
  name: erp-frontend
spec:
  selector:
    matchLabels:
      app: erp-frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: erp-frontend
    spec:
      containers:
        - name: erp-frontend
          image: erp-frontend:latest
          ports:
          - containerPort: 80
          imagePullPolicy: Never