apiVersion : apps/v1
kind: Deployment
metadata:
  name: basic-nodejs 
spec:
  selector:
    matchLabels:
      app: basic-nodejs 
  replicas: 1
  template:
    metadata:
      labels:
        app: basic-nodejs 
    spec:
      containers:
        - name: basic-nodejs 
          image: basic-nodejs
          ports:
          - containerPort: 3000
          imagePullPolicy: Never