apiVersion: v1
kind: Service
metadata:
    name: basic-nodejs
spec:
    type: ClusterIP
    ports:
    - protocol: "TCP"
      port: 3000
      targetPort: 3000
    selector:
        app: basic-nodejs
